### ISSUE TITLE
error in Ubuntu

### ISSUE THREAD

**Issue by iwoolf** [iamironman0/Whisper-Transcriber#3]
I installed the repo in Ubuntu 22.04LTS with git clone.
python setup.py worked.
python main.py gives the following error:
Traceback (most recent call last):
  File "/media/iwoolf/tenT/Whisper-Transcriber/main.py", line 8, in <module>
    from src.ui.add_subtitles import AddSubtitlesUI
  File "/media/iwoolf/tenT/Whisper-Transcriber/src/ui/add_subtitles.py", line 14, in <module>
    from .ctkAlert import CTkAlert
  File "/media/iwoolf/tenT/Whisper-Transcriber/src/ui/ctkAlert/__init__.py", line 1, in <module>
    from .ctkalert import CTkAlert
  File "/media/iwoolf/tenT/Whisper-Transcriber/src/ui/ctkAlert/ctkalert.py", line 9, in <module>
    "info": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\info_dark.png"),
  File "/media/iwoolf/BigDrive/anaconda3/envs/whisper/lib/python3.10/site-packages/PIL/Image.py", line 3243, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/iwoolf/tenT/Whisper-Transcriber/src/ui/ctkAlert\\icons\\info_dark.png'

**Comment by iamironman0** [comment]
### Try replacing this in file Whisper-Transcriber/src/ui/ctkAlert/ctkalert.py at line 8:

```
icons = {
    "info": ctk.CTkImage(dark_image=Image.open(f"{current_path}/icons/info_dark.png"),
                         light_image=Image.open(f"{current_path}/icons/info_light.png"), size=(28, 28)),
    "success": ctk.CTkImage(dark_image=Image.open(f"{current_path}/icons/success_dark.png"),
                            light_image=Image.open(f"{current_path}/icons/success_light.png"), size=(28, 28)),
    "error": ctk.CTkImage(dark_image=Image.open(f"{current_path}/icons/error_dark.png"),
                          light_image=Image.open(f"{current_path}/icons/error_light.png"), size=(28, 28)),
    "warning": ctk.CTkImage(dark_image=Image.open(f"{current_path}/icons/warning_dark.png"),
                            light_image=Image.open(f"{current_path}/icons/warning_light.png"), size=(28, 28))
}
```

> Just replace backslash with forwardslash

**Comment by Remus-Catrina** [comment]
After doing your change in the ctkalert.py 

This is the output:

/Whisper-Transcriber$ python main.py 
Traceback (most recent call last):
  File "/home/falken/Whisper-Transcriber/main.py", line 8, in <module>
    from src.ui.add_subtitles import AddSubtitlesUI
  File "/home/falken/Whisper-Transcriber/src/ui/add_subtitles.py", line 16, in <module>
    from .icons import icons
  File "/home/falken/Whisper-Transcriber/src/ui/icons.py", line 9, in <module>
    "close": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\close_dark.png"),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/falken/miniconda3/lib/python3.11/site-packages/PIL/Image.py", line 3243, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/falken/Whisper-Transcriber/src/ui\\icons\\close_dark.png'

**Comment by Remus-Catrina** [comment]
Then another issue with icons.py and main.py with similar \\ 

/Whisper-Transcriber/src/ui$ cat icons.py 
import os

import customtkinter as ctk
from PIL import Image

current_path = os.path.dirname(os.path.realpath(__file__))

icons = {
    "close": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\close_dark.png"),
                          light_image=Image.open(f"{current_path}\\icons\\close_light.png"), size=(30, 30)),
    "audio_file": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\audio_file_dark.png"),
                               light_image=Image.open(f"{current_path}\\icons\\audio_file_light.png"), size=(30, 30)),
    "translate": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\translation_dark.png"),
                              light_image=Image.open(f"{current_path}\\icons\\translate_light.png"), size=(30, 30)),
    "microphone": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\microphone_dark.png"),
                               light_image=Image.open(f"{current_path}\\icons\\microphone_light.png"), size=(30, 30)),
    "subtitle": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\subtitles_dark.png"),
                             light_image=Image.open(f"{current_path}\\icons\\subtitle_light.png"), size=(30, 30)),
    "settings": ctk.CTkImage(dark_image=Image.open(f"{current_path}\\icons\\settings_dark.png"),
                             light_image=Image.open(f"{current_path}\\icons\\settings_light.png"), size=(30, 30))
}


Replaced in main.py and the logo

then the following error appears:

python main.py 
Traceback (most recent call last):
  File "/home/falken/Whisper-Transcriber/main.py", line 177, in <module>
    app = Testing()
          ^^^^^^^^^
  File "/home/falken/Whisper-Transcriber/main.py", line 129, in __init__
    self.iconbitmap(logo)
  File "/home/falken/miniconda3/lib/python3.11/site-packages/customtkinter/windows/ctk_tk.py", line 232, in iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "/home/falken/miniconda3/lib/python3.11/tkinter/__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "/home/falken/Whisper-Transcriber/assets/icons/logo.ico" not defined

**Comment by iamironman0** [comment]
@Remus-Catrina The both error occurred because the icon file was not found, check if the icon/image is in right directory.

**Comment by iamironman0** [comment]
Also undo the changes i have said recently.
