### ISSUE TITLE
Use {os.path.sep} instead of \\.

### ISSUE THREAD

**Issue by NicHub** [iamironman0/Whisper-Transcriber#4]
To make the code portable to other OSes, use `{os.path.sep}` instead of `\\`.

**Comment by iamironman0** [comment]
@NicHub Could you make a pull request?

**Comment by NicHub** [comment]
Yes, no problem, I’ve created the pull request.

Note that in the tokenizer.py file, at line 253, there’s still an
occurrence of `\\`. I’ll leave it to you to see if it makes sense to
change it to `{os.path.sep}`.

**Comment by iamironman0** [comment]
Good job👍
